server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    
instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health